sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  matrix:
    - DJANGO="Django<1.9"
    - DJANGO="Django<1.10"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip wheel
  - pip install "$DJANGO" codecov
  - pip install .
branches:
  only:
    - master
script:
  - coverage run test_project/manage.py test
after_success:
  - coverage report
  - codecov